### ISSUE TITLE
Feature request: add external snapcast server support.

### ISSUE THREAD

**Issue by LaneaLucy** [Switch123456789/Switch-s-Home-Assistant-Add-ons#1]
Im using a external snapcast server on the same host and would love to use your mopidy plugin. If this is not possible, could you at least add snapcast server options to the config screen to add more streams? 
Thx

**Comment by Switch123456789** [comment]
Hey,
glad to see there is interest in my add-on :) I considered making snapcast a separate add-on but since I am inexperienced in creating add-ons/managing docker-containers it would take some time for me to figure things out. And time is fairly limited at the moment. However, I added an option to add more streams as you suggested. Just add all your streams separated with spaces in the new text-field in the configuration. I did not test it yet, so there is a chance it won't work at all :D Please let me know if it works for you.

**Comment by LaneaLucy** [comment]
You don't need to make your own snapcast server add-on, there are already multiple out there. You only need to add a new output option for external snapcast that's then output the mopidy fifo on the share folder, where another snapcast server add-on can grab it....

**Comment by Switch123456789** [comment]
I gotcha, my concern was mainly with using the share-folder or similar, since I do not know if the data is stored & red trough that file or if it just acts as some sort of interface. Because if it gets stored in said file, it would cause a lot of wear to the used storage-device (in my case a sensitive sd-card), while the tmp-folder is ram-based instead.

**Comment by LaneaLucy** [comment]
thats all no problem. other add-ons do it this way too.

**Comment by Switch123456789** [comment]
I finally came around to make some changes, now you can share audio through fifo "/share/mopidy" to use it on the host-system or another add-on.
![](https://github.com/Switch123456789/Switch-s-Home-Assistant-Add-ons/assets/25269380/036acc06-59de-47da-886f-3b901834c289)

Adding sources the mopidy add-ons snapserver should work too but I still didn't come around to test it.
![](https://github.com/Switch123456789/Switch-s-Home-Assistant-Add-ons/assets/25269380/fc821db4-1bf0-4cfc-aa28-3cba39d3827e)

I would appreciate feedback if you are going to try it :)

**Comment by Switch123456789** [comment]
It worked in my testing, so I will close the issue.

FYI: I did some research and it turned out that the data indeed gets written to the to the sd-card (or whatever storage device is used for HA) before getting picked up from snapcast. Therefor I highly recommend to use the snapcast-server included in my add-on, it is configured to use a ram-drive which can't be shared with another add-on (as far as I know).
